package com.mfrankic.sketchid;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Represents a single data point from the magnetic field sensor.
 * This class is an Entity for the Room persistence library, stored in the "magnetic_field_data"
 * table.
 * It includes foreign keys to {@link User} and {@link Image} entities (though not explicitly
 * defined
 * with @ForeignKey here, they are typically joined in DAO queries) and indices for performance.
 */
@Entity(
    tableName = "magnetic_field_data",
    indices = {@Index("user_id"), @Index("image_id"), @Index("session_id"), @Index("attempt")},
    foreignKeys = {
        @ForeignKey(
            entity = User.class,
            parentColumns = "id",
            childColumns = "user_id",
            onDelete = ForeignKey.CASCADE
        ), @ForeignKey(
        entity = Image.class,
        parentColumns = "id",
        childColumns = "image_id",
        onDelete = ForeignKey.CASCADE
    )
    }
)
public class MagneticFieldData {

  /**
   * The unique identifier for this magnetic field data record.
   * Auto-generated by the database.
   */
  @PrimaryKey(autoGenerate = true)
  public int id;

  /**
   * The ID of the user associated with this data.
   */
  @ColumnInfo(name = "user_id")
  public int userId;

  /**
   * The ID of the image being drawn when this data was recorded.
   */
  @ColumnInfo(name = "image_id")
  public int imageId;

  /**
   * A unique identifier for the drawing session.
   */
  @ColumnInfo(name = "session_id")
  public String sessionId;

  /**
   * The attempt number within the session.
   */
  @ColumnInfo(name = "attempt")
  public int attempt;

  /**
   * The timestamp (in milliseconds) when this data point was recorded.
   */
  @ColumnInfo(name = "timestamp")
  public long timestamp;

  /**
   * Magnetic field strength on the X-axis in micro-Tesla (μT).
   */
  @ColumnInfo(name = "x")
  public float x;

  /**
   * Magnetic field strength on the Y-axis in micro-Tesla (μT).
   */
  @ColumnInfo(name = "y")
  public float y;

  /**
   * Magnetic field strength on the Z-axis in micro-Tesla (μT).
   */
  @ColumnInfo(name = "z")
  public float z;

  /**
   * Default constructor required by Room.
   */
  public MagneticFieldData() {
  }

  /**
   * Constructs a new {@link MagneticFieldData} object.
   * This constructor is ignored by Room and is intended for manual object creation.
   *
   * @param userId    The ID of the user.
   * @param imageId   The ID of the image.
   * @param sessionId The session identifier.
   * @param attempt   The attempt number.
   * @param timestamp The recording timestamp.
   * @param x         Magnetic field strength on the X-axis.
   * @param y         Magnetic field strength on the Y-axis.
   * @param z         Magnetic field strength on the Z-axis.
   */
  @Ignore
  public MagneticFieldData(
      int userId,
      int imageId,
      String sessionId,
      int attempt,
      long timestamp,
      float x,
      float y,
      float z
  ) {
    this.userId = userId;
    this.imageId = imageId;
    this.sessionId = sessionId;
    this.attempt = attempt;
    this.timestamp = timestamp;
    this.x = x;
    this.y = y;
    this.z = z;
  }
} 
