package com.mfrankic.sketchid;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Represents a single record of magnetic field baseline data collected by the application.
 * This data is typically gathered before a drawing session to establish a baseline reading
 * of the ambient magnetic field.
 * <p>
 * This class is an Entity for the Room persistence library, stored in the
 * "magnetic_field_baseline_data" table. It includes foreign keys to {@link User} and {@link Image}
 * entities, and indices for faster querying.
 */
@Entity(
    tableName = "magnetic_field_baseline_data", foreignKeys = {
    @ForeignKey(
        entity = User.class,
        parentColumns = "id",
        childColumns = "user_id",
        onDelete = ForeignKey.CASCADE
        // Delete baseline data if the associated user is deleted
        ), @ForeignKey(
    entity = Image.class,
    parentColumns = "id",
    childColumns = "image_id",
    onDelete = ForeignKey.CASCADE
    // Delete baseline data if the associated image is deleted
    )
}, indices = {
    @Index("user_id"), @Index("image_id"), @Index("session_id"), @Index("attempt")
}
)
public class MagneticFieldBaselineData {
  /**
   * The unique identifier for this baseline data record.
   * Auto-generated by the database.
   */
  @PrimaryKey(autoGenerate = true)
  public long id;

  /**
   * The ID of the user associated with this baseline data. Foreign key to {@link User#id}.
   */
  @ColumnInfo(name = "user_id")
  public long userId;

  /**
   * The ID of the image associated with this baseline data. Foreign key to {@link Image#id}.
   */
  @ColumnInfo(name = "image_id")
  public int imageId;

  /**
   * A unique identifier for the session during which this baseline data was recorded.
   */
  @ColumnInfo(name = "session_id")
  public String sessionId;

  /**
   * The attempt number within the session for which this baseline data was recorded.
   */
  @ColumnInfo(name = "attempt")
  public int attempt;

  /**
   * The timestamp (in milliseconds) when this baseline data was recorded.
   */
  @ColumnInfo(name = "timestamp")
  public long timestamp;

  /**
   * The average magnetic field strength on the X-axis during the baseline period.
   */
  @ColumnInfo(name = "avg_x")
  public float avgX;

  /**
   * The average magnetic field strength on the Y-axis during the baseline period.
   */
  @ColumnInfo(name = "avg_y")
  public float avgY;

  /**
   * The average magnetic field strength on the Z-axis during the baseline period.
   */
  @ColumnInfo(name = "avg_z")
  public float avgZ;

  /**
   * The duration (in milliseconds) over which this baseline data was collected.
   */
  @ColumnInfo(name = "duration_ms")
  public long durationMs;

  /**
   * The number of samples collected to calculate this baseline.
   */
  @ColumnInfo(name = "sample_count")
  public int sampleCount;

  /**
   * The standard deviation of magnetic field strength on the X-axis.
   */
  @ColumnInfo(name = "std_dev_x")
  public float stdDevX;

  /**
   * The standard deviation of magnetic field strength on the Y-axis.
   */
  @ColumnInfo(name = "std_dev_y")
  public float stdDevY;

  /**
   * The standard deviation of magnetic field strength on the Z-axis.
   */
  @ColumnInfo(name = "std_dev_z")
  public float stdDevZ;

  /**
   * Constructs a new {@link MagneticFieldBaselineData} object.
   *
   * @param userId      The ID of the user.
   * @param imageId     The ID of the image.
   * @param sessionId   The session identifier.
   * @param attempt     The attempt number.
   * @param timestamp   The recording timestamp.
   * @param avgX        Average X-axis magnetic field.
   * @param avgY        Average Y-axis magnetic field.
   * @param avgZ        Average Z-axis magnetic field.
   * @param durationMs  Duration of baseline collection in milliseconds.
   * @param sampleCount Number of samples collected.
   * @param stdDevX     Standard deviation of X-axis magnetic field.
   * @param stdDevY     Standard deviation of Y-axis magnetic field.
   * @param stdDevZ     Standard deviation of Z-axis magnetic field.
   */
  public MagneticFieldBaselineData(
      long userId,
      int imageId,
      String sessionId,
      int attempt,
      long timestamp,
      float avgX,
      float avgY,
      float avgZ,
      long durationMs,
      int sampleCount,
      float stdDevX,
      float stdDevY,
      float stdDevZ
  ) {
    this.userId = userId;
    this.imageId = imageId;
    this.sessionId = sessionId;
    this.attempt = attempt;
    this.timestamp = timestamp;
    this.avgX = avgX;
    this.avgY = avgY;
    this.avgZ = avgZ;
    this.durationMs = durationMs;
    this.sampleCount = sampleCount;
    this.stdDevX = stdDevX;
    this.stdDevY = stdDevY;
    this.stdDevZ = stdDevZ;
  }
} 
