package com.mfrankic.sketchid;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a user in the application.
 * This class is an Entity for the Room persistence library, stored in the "user" table.
 */
@Entity(tableName = "user")
public class User {

  /**
   * The unique identifier for the user.
   * This field is the primary key and is auto-generated by the database.
   */
  @PrimaryKey(autoGenerate = true)
  public int id;

  /**
   * The name of the user.
   */
  @ColumnInfo(name = "name")
  public String name;

  /**
   * Constructs a new User with the given name.
   *
   * @param name The name of the user.
   */
  public User(String name) {
    this.name = name;
  }

  /**
   * Returns a string representation of the User, which is their name.
   *
   * @return The name of the user.
   */
  @NonNull
  @Override
  public String toString() {
    return name;
  }
}
