package com.mfrankic.sketchid;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Before;
import org.junit.Test;

/**
 * Unit tests for User class.
 * Tests constructor, field access, and toString functionality.
 */
public class UserTest {

  private User user;

  @Before
  public void setup() {
    user = new User("TestUser");
  }

  @Test
  public void testConstructorWithValidName() {
    String testName = "John Doe";
    User testUser = new User(testName);

    assertEquals("Name should match constructor parameter", testName, testUser.name);
  }

  @Test
  public void testConstructorWithNullName() {
    User nullUser = new User(null);
    assertNull("Null name should be handled", nullUser.name);
  }

  @Test
  public void testConstructorWithEmptyName() {
    User emptyUser = new User("");
    assertEquals("Empty name should be handled", "", emptyUser.name);
  }

  @Test
  public void testNameFieldAccess() {
    assertEquals("Name field should be accessible", "TestUser", user.name);
  }

  @Test
  public void testNameFieldModification() {
    String newName = "ModifiedUser";
    user.name = newName;
    assertEquals("Name field should be modifiable", newName, user.name);
  }

  @Test
  public void testIdFieldInitialization() {
    // ID field should start at 0 (auto-generated by Room)
    assertEquals("ID field should be initialized to 0", 0, user.id);
  }

  @Test
  public void testIdFieldModification() {
    int newId = 123;
    user.id = newId;
    assertEquals("ID field should be modifiable", newId, user.id);
  }

  @Test
  public void testToStringWithValidName() {
    assertEquals("toString should return the name", "TestUser", user.toString());
  }

  @Test
  public void testToStringWithModifiedName() {
    user.name = "ChangedName";
    assertEquals("toString should return updated name", "ChangedName", user.toString());
  }

  @Test
  public void testToStringWithNullName() {
    user.name = null;
    assertNull("toString should return null for null name", user.toString());
  }

  @Test
  public void testToStringWithEmptyName() {
    user.name = "";
    assertEquals("toString should return empty string", "", user.toString());
  }

  @Test
  public void testToStringWithSpecialCharacters() {
    String specialName = "@#$%^&*()";
    user.name = specialName;
    assertEquals("toString should handle special characters", specialName, user.toString());
  }

  @Test
  public void testToStringWithUnicodeCharacters() {
    String unicodeName = "用户测试";
    user.name = unicodeName;
    assertEquals("toString should handle unicode characters", unicodeName, user.toString());
  }

  @Test
  public void testToStringWithLongName() {
    String longName = "This is a very long user name that might be used to test string handling";
    user.name = longName;
    assertEquals("toString should handle long names", longName, user.toString());
  }

  @Test
  public void testMultipleUsers() {
    User user1 = new User("User1");
    User user2 = new User("User2");

    assertEquals("First user name should be correct", "User1", user1.name);
    assertEquals("Second user name should be correct", "User2", user2.name);
    assertEquals("First user toString should be correct", "User1", user1.toString());
    assertEquals("Second user toString should be correct", "User2", user2.toString());
  }

  @Test
  public void testUserIndependence() {
    User user1 = new User("Original");
    User user2 = new User("Original");

    // Modify one user
    user1.name = "Modified";
    user1.id = 100;

    // Other user should remain unchanged
    assertEquals("Second user name should remain unchanged", "Original", user2.name);
    assertEquals("Second user ID should remain unchanged", 0, user2.id);
    assertEquals("Second user toString should remain unchanged", "Original", user2.toString());
  }

  @Test
  public void testNameWithWhitespace() {
    String nameWithSpaces = "  User With Spaces  ";
    User spacedUser = new User(nameWithSpaces);
    assertEquals("Name with spaces should be preserved", nameWithSpaces, spacedUser.name);
    assertEquals("toString should preserve spaces", nameWithSpaces, spacedUser.toString());
  }

  @Test
  public void testNameWithNewlines() {
    String nameWithNewlines = "User\nWith\nNewlines";
    User newlineUser = new User(nameWithNewlines);
    assertEquals("Name with newlines should be preserved", nameWithNewlines, newlineUser.name);
    assertEquals("toString should preserve newlines", nameWithNewlines, newlineUser.toString());
  }

  @Test
  public void testNameWithTabs() {
    String nameWithTabs = "User\tWith\tTabs";
    User tabUser = new User(nameWithTabs);
    assertEquals("Name with tabs should be preserved", nameWithTabs, tabUser.name);
    assertEquals("toString should preserve tabs", nameWithTabs, tabUser.toString());
  }

  @Test
  public void testIdBoundaryValues() {
    // Test various ID values
    int[] testIds = {0, 1, -1, Integer.MAX_VALUE, Integer.MIN_VALUE, 100, 999, 1000};

    for (int testId : testIds) {
      User testUser = new User("TestUser");
      testUser.id = testId;
      assertEquals("ID " + testId + " should be handled correctly", testId, testUser.id);
    }
  }

  @Test
  public void testTypicalUserScenarios() {
    // Test common real-world user names
    String[] commonNames = {
        "John Smith",
        "María García",
        "李小明",
        "Ahmed Al-Hassan",
        "Jean-Pierre Dupont",
        "O'Connor",
        "van der Berg",
        "Smith-Jones"
    };

    for (String commonName : commonNames) {
      User testUser = new User(commonName);
      assertEquals("Common name should be handled: " + commonName, commonName, testUser.name);
      assertEquals(
          "toString should work for common name: " + commonName,
          commonName,
          testUser.toString()
      );
    }
  }

  @Test
  public void testUserFieldsAfterMultipleChanges() {
    // Test multiple modifications to verify fields work correctly
    user.name = "First";
    user.id = 1;
    assertEquals("First name change should work", "First", user.name);
    assertEquals("First ID change should work", 1, user.id);
    assertEquals("First toString should work", "First", user.toString());

    user.name = "Second";
    user.id = 2;
    assertEquals("Second name change should work", "Second", user.name);
    assertEquals("Second ID change should work", 2, user.id);
    assertEquals("Second toString should work", "Second", user.toString());

    user.name = null;
    user.id = 0;
    assertNull("Setting name to null should work", user.name);
    assertEquals("Setting ID to 0 should work", 0, user.id);
    assertNull("toString with null should return null", user.toString());
  }

  @Test
  public void testConsistencyBetweenNameAndToString() {
    // Verify that toString always returns the current value of name
    String[] testNames = {"Test", "", "Changed", "Final"};

    for (String testName : testNames) {
      user.name = testName;
      assertEquals("toString should match name: " + testName, testName, user.toString());
    }

    // Test null case separately
    user.name = null;
    assertNull("toString should match name (null case)", user.toString());
  }

  @Test
  public void testNumericStringNames() {
    // Test names that are numeric strings
    String[] numericNames = {"123", "0", "-1", "999999", "1.5", "3.14"};

    for (String numericName : numericNames) {
      User numericUser = new User(numericName);
      assertEquals(
          "Numeric string name should be handled: " + numericName,
          numericName,
          numericUser.name
      );
      assertEquals(
          "toString should work for numeric name: " + numericName,
          numericName,
          numericUser.toString()
      );
    }
  }
} 
